version: '3.9'
services:
  mailboxmanager:
    image: jeanlucasb/mail-box-manager
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /MailBoxManager
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:h2:mem:mailBoxManager;DB_CLOSE_DELAY=-1
      SPRING_DATASOURCE_DRIVER_CLASSNAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      SPRING_H2_CONSOLE_PATH: /h2-console
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
      SPRING_H2_CONSOLE_ENABLED: true
      SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: true
      SERVER_PORT: 8080
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    networks:
      - app-network
networks:
  app-network:
    driver: bridge